[versions]
asciidoctorj = "2.5.7"
commons-io = "2.11.0"
freemarker = "2.3.32"
jbake = "2.6.7"
jetty = "9.4.44.v20210927"
jffi = "1.3.9"
jna = "5.14.0"
jnr-constants = "0.10.3"
jnr-posix = "3.1.15"
jruby = "9.4.5.0"
pegdown = "1.6.0"

[libraries]

[bundles]


[plugins]
git-publish = { id = "org.ajoberstar.git-publish", version = "4.2.2" }
gretty = { id = "org.gretty", version = "4.1.2" }
jbake-site =  { id = "org.jbake.site", version = "5.5.0" }